// Segundo_Periodo/Aprofundamento_em_Desenvolvimento_Front_end/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.css'],
  standalone: false
})
export class LivroDadosComponent implements OnInit {
  public livro: Livro = new Livro(0, 0, '', '', []);
  public autoresForm: string = '';
  public editoras: Array<Editora> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) { }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = (): void => {
    this.livro.autores = this.autoresForm.split('\n');
    this.servLivros.incluir(this.livro);
    this.router.navigateByUrl('/lista');
  }
}

<main class="container">
  <h1>Dados do Livro</h1>
  <form (submit)="incluir()" ngNativeValidate>
    <div class="mb-3">
      <label for="titulo" class="form-label">Título</label>
      <input type="text" class="form-control" id="titulo" [(ngModel)]="livro.titulo" name="titulo" required>
    </div>
    
    <div class="mb-3">
      <label for="resumo" class="form-label">Resumo</label>
      <textarea class="form-control" id="resumo" rows="3" [(ngModel)]="livro.resumo" name="resumo" required></textarea>
    </div>
    
    <div class="mb-3">
      <label for="editora" class="form-label">Editora</label>
      <select class="form-select" id="editora" [(ngModel)]="livro.codEditora" name="codEditora" required>
        <option *ngFor="let editora of editoras" [ngValue]="editora.codEditora">
          {{ editora.nome }}
        </option>
      </select>
    </div>
    
    <div class="mb-3">
      <label for="autores" class="form-label">Autores (1 por linha)</label>
      <textarea class="form-control" id="autores" rows="3" [(ngModel)]="autoresForm" name="autoresForm" required></textarea>
    </div>
    
    <button type="submit" class="btn btn-primary">Salvar</button>
  </form>
</main>

// Segundo_Periodo/Integracao_de_Paginas_Web_com_Banco_de_Dados/clientes/livros-react/src/LivroDados.js
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import ControleEditora from './controle/ControleEditora';
import ControleLivros from './controle/ControleLivros';

const LivroDados = () => {

  const controleLivro = new ControleLivros();
  const controleEditora = new ControleEditora();

  const opcoes = controleEditora.getEditoras().map(editora => ({
    value: editora.codEditora,
    text: editora.nome,
  }));

  const [titulo, setTitulo] = useState('');
  const [resumo, setResumo] = useState('');
  const [autores, setAutores] = useState('');
  const [codEditora, setCodEditora] = useState(opcoes.length > 0 ? opcoes[0].value : '');

  const navigate = useNavigate();

  const tratarCombo = (event) => {
    setCodEditora(Number(event.target.value));
  };

  const incluir = (event) => {
    event.preventDefault();

    const autoresArray = autores.split('\n').map(autor => autor.trim());

    const novoLivro = {
      codigo: "",
      titulo: titulo,
      resumo: resumo,
      autores: autoresArray,
      codEditora: codEditora,
    };

    controleLivro.incluir(novoLivro).then(() => {
      navigate('/');
    });
  };

  return (
    <main className='container'>
      <h1>Dados do Livro</h1>
      <form onSubmit={incluir}>
        <div className='form-group mb-3'>
          <label htmlFor='titulo'>Título</label>
          <input 
            type='text'
            id='titulo'
            className='form-control'
            value={titulo}
            onChange={(e) => setTitulo(e.target.value)}required
          />
        </div>
        <div className='form-group mb-3'>
          <label htmlFor='resumo'>Resumo</label>
          <textarea 
            id='resumo'
            className='form-control'
            value={resumo}
            onChange={(e) => setResumo(e.target.value)}required
          />
        </div>
        <div className='form-group mb-3'>
          <label htmlFor='editora'>Editora</label>
          <select 
            id='editora'
            className='form-control'
            value={codEditora}
            onChange={tratarCombo}
          >
            {opcoes.map((opcao) => (
              <option key={opcao.value} value={opcao.value}>
                {opcao.text}
              </option>
            ))}
            </select>
        </div>
        <div className='form-group mb-3'>
          <label>Autores</label>
          <textarea 
            id='autores'
            className='form-control'
            value={autores}
            onChange={(e) => setAutores(e.target.value)}required
          />
        </div>
        
        <button type='submit' className='btn btn-primary'>
          Salvar Dados
        </button>
      </form>
    </main>
  );
};

export default LivroDados;
