// Segundo_Periodo/Integracao_de_Paginas_Web_com_Banco_de_Dados/clientes/livros-react/src/LivroLista.js
import { useState, useEffect } from "react";
import ControleLivros from "./controle/ControleLivros";
import ControleEditora from "./controle/ControleEditora"

function LinhaLivro(props) {
  const {livro, excluir, controleEditora} = props;
  const nomeEditora = controleEditora.getNomeEditora(livro.codEditora);  
  
  return (
    <tr>
      <td>{livro.titulo}<br />
        <button className="btn btn-sm btn-danger" onClick={() => excluir(livro.codigo)}>
          Excluir
        </button>
      </td>
      <td>{livro.resumo}</td>
      <td>{nomeEditora}</td>
      <td></td>
      <td>
        <ul>{livro.autores.map((autor, index) => (<li key={index}>{autor}</li>))}</ul>
      </td>
    </tr>
  );
};

export default function LivroLista() {
  const [livros, setLivros] = useState([]);
  const [carregado, setCarregado] = useState(false);

  
  const controleEditora = new ControleEditora();

  useEffect(() => {
    if (!carregado) {
      const controleLivro = new ControleLivros();
      controleLivro.obterLivros().then((resultado) => {
        setLivros(resultado);
        setCarregado(true);
      });
    }
  }, [carregado]); 

  const excluir = async (codigo) => {
    const controleLivro = new ControleLivros();
    await controleLivro.excluir(codigo).then(() => setCarregado(false));
  };
  
  return (
    <main className="container">
      <h1 className="text-start">Catálogo de Livros</h1>
      <table className="table table-striped">
        <thead className="table-dark text-start"> 
          <tr>
            <th>Título</th>
            <th>Resumo</th>
            <th>Editora</th>
            <th></th>
            <th>Autores</th>
          </tr>
        </thead>
        <tbody className="text-start">
          {Array.isArray(livros) && livros.length > 
          0 ? (
            carregado && livros.map((livro, index) => (
              <LinhaLivro
                key={index}
                livro={livro}
                excluir={excluir}
                controleEditora={controleEditora}
              />
            ))
          ) : (
            <tr>
              <td colSpan={5}>Nenhum livro encontrado.</td>
            </tr>
          )}
        </tbody>
      </table>
    </main>
  );
};

// Segundo_Periodo/Aprofundamento_em_Desenvolvimento_Front_end/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Editora } from '../editora';
import { Livro } from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.css'],
  standalone: false
})
export class LivroListaComponent implements OnInit {
  public editoras: Array<Editora> = [];
  public livros: Array<Livro> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService
  ) { }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.livros = this.servLivros.obterLivros();
  }

  excluir = (codigo: number): void => {
    this.servLivros.excluir(codigo);
    this.livros = this.servLivros.obterLivros();
  }

  obterNome = (codEditora: number): string => {
    return this.servEditora.getNomeEditora(codEditora);
  }
}

<main class="container">
  <h1>Catálogo de Livros</h1>
  <table class="table table-striped">
    <thead class="table-dark">
      <tr>
        <th>Título</th>
        <th>Resumo</th>
        <th>Editora</th>
        <th>Autores</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let livro of livros">
        <td>
          {{ livro.titulo }}<br>
          <button class="btn btn-danger btn-sm" (click)="excluir(livro.codigo)">Excluir</button>
        </td>
        <td>{{ livro.resumo }}</td>
        <td>{{ obterNome(livro.codEditora) }}</td>
        <td>
          <ul>
            <li *ngFor="let autor of livro.autores">{{ autor }}</li>
          </ul>
        </td>
      </tr>
    </tbody>
  </table>
</main>
